---
- hosts: vm
  vars:
    users:
      - jaime
      - sansa
      - robert
  tasks:
    - name: Create users
      loop: "{{ users }}"
      ansible.builtin.user:
        name: "{{ item }}"
      become: yes

    - name: Copy authorized ssh
      ansible.posix.authorized_key:
        key: "{{ lookup('file', '../files/ansible.pub') }}"
        user: "{{ item }}"
      loop: "{{ users }}"
      become: yes

    - name: Create git configs
      loop: "{{ users }}"
      ansible.builtin.template:
        src: ../templates/gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
      become: yes
