---
- hosts: vm
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install initial packages
      ansible.builtin.apt:
        pkg:
          - git
          - make
          - nodejs
        state: present
        update_cache: yes
      tags: apps
      become: yes

    - name: Add users
      loop:
        - arya
        - sansa
        - tirion
      ansible.builtin.user:
        name: "{{ item }}"
      tags: users
      become: yes
